#!/bin/bash

    for NC in ${NCAUSAL}; do
        for MU in ${MUVAR}; do
            BLORE_META_FEAT_JOBNAME="blore_meta_feat_${SIM}_${RANDSTRING}_${NC}_mu${MU}"
            sed "s|_JOBNAME|${BLORE_META_FEAT_JOBNAME}|g;
                 s|_SIMDIR_|${THIS_SIMDIR}|g;
                 s|_NCAUSAL|${NC}|g;
                 s|_FEATDIR|${ANNOTDIR}|g;
                 s|_STUDYN_|\"${STUDYNAMES[*]}\"|g;
                 s|_MU_VAR_|${MU}|g;
                 s|_B_LORE_|${BLORE}|g;" ${MASTER_JOBSUBDIR}/blore_with_features.bsub > ${BLORE_META_FEAT_JOBNAME}.bsub
            if [[ ${CHAIN_JOBS} == "True" ]]; then
                bsub -w "done(${BLORE_SUMMARY_JOBNAME}*)" < ${BLORE_META_FEAT_JOBNAME}.bsub
            else
                bsub < ${BLORE_META_FEAT_JOBNAME}.bsub
            fi
        done
    done
