#!/bin/bash

    # Create phenotype ================================================================
    PHENO_JOBNAME="pheno_${SIM}_${RANDSTRING}"
    sed -e "s|_JOBNAME|${PHENO_JOBNAME}|g;
            s|_LOCIDIR|${DOSAGEDIR}|g;
            s|_FEATDIR|${ANNOTDIR}|g;
            s|_SIMDIR_|${THIS_SIMDIR}|g;
            s|_LOCUSN_|${LOCUSNAMES}|g;
            s|_SCRIPT_|${CREATEPHENO}|g;
            s|_STUDYN_|\"${STUDYNAMES[*]}\"|g;
            s|_SAMPLES|\"${STUDYSAMPLES[*]}\"|g;
            s|_HGSQUR_|${HERITABILITY}|g;
            s|_SIMTYPE|${PHENO_SIM_TYPE}|g;
            s|_C_PROP_|${C_PROP}|g;" ${MASTER_JOBSUBDIR}/create_phenotype_with_dhs.bsub > ${PHENO_JOBNAME}.bsub
    bsub < ${PHENO_JOBNAME}.bsub
    # =================================================================================
