#!/bin/bash

    # Run JAM  ========================================================================
    if [ ! -d jam ];then mkdir jam; fi
    cd jam
    JAM_JOBNAME="jam_${SIM}_${RANDSTRING}"
    sed "s|_JOBNAME|${JAM_JOBNAME}|g;
         s|_SIMDIR_|${THIS_SIMDIR}|g;
         s|_LOCUSN_|${LOCUSNAMES}|g;
         s|_LOCIDIR|${JAM_COMBINED_LOCIDIR}|g;
         s|_LD_DIR_|${JAM_COMBINED_LDDIR}|g;
         s|_R_JAM__|${JAMSCRIPT}|g;" ${MASTER_JOBSUBDIR}/jam_fatplus.bsub > ${JAM_JOBNAME}.bsub
    if [[ ${CHAIN_JOBS} == "True" ]]; then
        bsub -w "done(${SNPTEST_JOBNAME}*)" < ${JAM_JOBNAME}.bsub
    else
        bsub < ${JAM_JOBNAME}.bsub
    fi
    cd ..
    # =================================================================================
