#!/bin/bash

    # Run PIMASS  ======================================================================
    for NC in ${NPIMASS}; do
        PIMASS_JOBSUBDIR="${THIS_JOBSUBDIR}/pimass_c${NC}_5e6"
        if [ -d ${PIMASS_JOBSUBDIR} ]; then rm -rf ${PIMASS_JOBSUBDIR}; fi
        mkdir -p ${PIMASS_JOBSUBDIR}
        cd ${PIMASS_JOBSUBDIR}

        for LOCUSPREFIX in ${LOCIPREFIX[@]}; do
            PIMASS_JOBNAME="pimass_${SIM}_c${NC}_${LOCUSPREFIX}_${RANDSTRING}"
            sed -e "s|_JOBNAME|${PIMASS_JOBNAME}|g;
                    s|_SIMDIR_|${THIS_SIMDIR}|g;
                    s|_STUDYN_|\"${STUDYNAMES[*]}\"|g;
                    s|_LOCUSP_|${LOCUSPREFIX}|g;
                    s|_LOCIDIR|${DOSAGEDIR}|g;
                    s|_NCAUSAL|${NC}|g;
                    s|_PIMASS_|${PIMASS}|g;" ${MASTER_JOBSUBDIR}/mcmc_pimass.bsub > ${PIMASS_JOBNAME}.bsub
            if [[ ${CHAIN_JOBS} == "True" ]]; then
                bsub -w "done(${PHENO_JOBNAME})" < ${PIMASS_JOBNAME}.bsub
                #echo "${THIS_SIMDIR} ${LOCUSPREFIX} ${PIMASS_JOBNAME}"
            else
                bsub < ${PIMASS_JOBNAME}.bsub
                #echo "${THIS_SIMDIR} ${LOCUSPREFIX} ${PIMASS_JOBNAME}"
            fi
        done
        cd ${THIS_JOBSUBDIR}
    done
    # =================================================================================
