#!/bin/bash

    # Run METASKAT ====================================================================
    METASKAT_JOBNAME="metaskat_${SIM}_${RANDSTRING}"
    sed "s|_JOBNAME|${METASKAT_JOBNAME}|g;
         s|_SIMDIR_|${THIS_SIMDIR}|g;
         s|_STUDYN_|\"${STUDYNAMES[*]}\"|g;
         s|_LOCUSN_|${LOCUSNAMES}|g;
         s|_LOCIDIR|${DOSAGEDIR}|g;
         s|_MSKAT__|${METASKAT}|g;" ${MASTER_JOBSUBDIR}/metaskat.bsub > ${METASKAT_JOBNAME}.bsub
    if [[ ${CHAIN_JOBS} == "True" ]]; then
        bsub -w "done(${PHENO_JOBNAME})" < ${METASKAT_JOBNAME}.bsub
    else
        bsub < ${METASKAT_JOBNAME}.bsub
    fi
    # =================================================================================
