#!/bin/bash

    # Run META ========================================================================
    META_JOBNAME="meta_${SIM}_${RANDSTRING}"
    sed "s|_JOBNAME|${META_JOBNAME}|g;
         s|_SIMDIR_|${THIS_SIMDIR}|g;
         s|_STUDYN_|\"${STUDYNAMES[*]}\"|g;
         s|_SAMPLES|\"${STUDYSAMPLES[*]}\"|g;
         s|_LOCUSN_|${LOCUSNAMES}|g;
         s|_SCRIPT_|${GENINF}|g;
         s|__META__|${META}|g;" ${MASTER_JOBSUBDIR}/meta.bsub > ${META_JOBNAME}.bsub
    if [[ ${CHAIN_JOBS} == "True" ]]; then
        bsub -w "done(${SNPTEST_JOBNAME}*)" < ${META_JOBNAME}.bsub
    else
        bsub < ${META_JOBNAME}.bsub
    fi
    # =================================================================================
