#!/bin/bash

    # Calculate genomic inflation factor ==============================================
    GENINF_JOBNAME="geninf_${SIM}_${RANDSTRING}"
    sed "s|_JOBNAME|${GENINF_JOBNAME}|g;
         s|_SIMDIR_|${THIS_SIMDIR}|g;
         s|_STUDYN_|\"${STUDYNAMES[*]}\"|g;
         s|_SAMPLES|\"${STUDYSAMPLES[*]}\"|g;
         s|_LOCUSN_|${LOCUSNAMES}|g;
         s|_SCRIPT_|${GENINF}|g;" ${MASTER_JOBSUBDIR}/gen_inflation.bsub > ${GENINF_JOBNAME}.bsub
    bsub -w "done(${SNPTEST_JOBNAME}*)" < ${GENINF_JOBNAME}.bsub
    # =================================================================================
