#!/bin/bash

# Submit SNPTEST ==================================================================
SNPTEST_JOBNAME="snptest_${SIM}_${RANDSTRING}"
for STUDY in ${STUDYNAMES[@]}; do
    JOBNAME="${SNPTEST_JOBNAME}_${STUDY}"
    sed "s|_JOBNAME|${JOBNAME}|g;
         s|_SIMDIR_|${THIS_SIMDIR}|g;
         s|_GSTUDY_|${STUDY}|g;
         s|_SNPTEST|${SNPTEST}|g;
         s|_LOCIDIR|${DOSAGEDIR}|" ${MASTER_JOBSUBDIR}/snptest.bsub > ${JOBNAME}.bsub
    bsub -w "done(${PHENO_JOBNAME})" < ${JOBNAME}.bsub
done
# =================================================================================
