#!/bin/bash

CURDIR=`pwd`

# data directories
BASEDIR="/scratch/sbanerj/quasi_laplace_gwas/simulated_phenotype/mcmc_vs_qL"
DOSAGEDIR="${BASEDIR}/loci_dosages"
SIMDIR="${BASEDIR}/simulations"
STUDYNAMES=('G1' 'G2' 'G3' 'G4' 'G5')
STUDYSAMPLES=('2139' '2420' '2472' '2084' '3967')
LOCUSNAMES="${BASEDIR}/LOCUSNAMES"

# Pipeline directories
MASTER_JOBSUBDIR="${CURDIR}/../jobsubfiles"
JOBSUBDIR="${CURDIR}/mcmc_vs_qL"
SCRIPTDIR="${CURDIR}/../scripts"

# external programs required for the pipeline
BLORE="${HOME}/fine-mapping-SNPs/codebase/b-lore/bin/blore"
PIMASS="${HOME}/packages/pimass/pimass"
GEMMA="gemma"

# other scripts used in the pipeline
CREATEPHENO="${SCRIPTDIR}/create_phenotype.py"

START=1
END=10
NCAUSAL=2
HERITABILITY=0.4
C_PROP=0.01
NSAMPLE_TOT=13082
NGEMMA="2"
PHENO_SIM_TYPE="fixed" # fixed, bimodal, studentsT
