#!/bin/bash

CURDIR=`pwd`

# data directories
BASEDIR="/scratch/sbanerj/quasi_laplace_gwas/simulated_phenotype/mcmc_vs_qL"
DOSAGEDIR="${BASEDIR}/loci_dosages"
ANNOTDIR="${BASEDIR}/functional_annotations"
LDMAPDIR="${BASEDIR}/ldmap"
SIMDIR="${BASEDIR}/simulations"
STUDYNAMES=('G1' 'G2' 'G3' 'G4' 'G5')
STUDYSAMPLES=('2139' '2420' '2472' '2084' '3967')
LOCUSNAMES="${BASEDIR}/LOCUSNAMES"

# External files
FEATURE_CORRELATION="${ANNOTDIR}/func_annot_corr.dat"
FEATURE_NAMES="${ANNOTDIR}/functional_annotation_names.dat"

# Pipeline directories
MASTER_JOBSUBDIR="${CURDIR}/../jobsubfiles"
JOBSUBDIR="${CURDIR}/mcmc_vs_qL"
SCRIPTDIR="${CURDIR}/../scripts"

# external programs required for the pipeline
LDSTORE="${HOME}/packages/ldstore/ldstore_v1.1_x86_64/ldstore"
SNPTEST="${HOME}/packages/SNPTEST/snptest_v2.5.4-beta3_linux_x86_64_dynamic/snptest_v2.5.4-beta3"
META="${HOME}/packages/META/meta"
BIMBAM="${HOME}/packages/BIMBAM/bimbam/bimbam"
BLORE="${HOME}/fine-mapping-SNPs/codebase/b-lore/bin/blore"
PAINTOR="${HOME}/packages/PAINTOR/PAINTOR_V3.0-master/PAINTOR"
CAVIARBF="${HOME}/packages/CAVIARBF/Wenan-caviarbf-7e428645be5e/caviarbf"
MODEL_SEARCH="${HOME}/packages/CAVIARBF/Wenan-caviarbf-7e428645be5e/model_search"
FINEMAP="${HOME}/packages/FINEMAP/finemap_v1.1_x86_64/finemap"

# other scripts used in the pipeline
CREATEPHENO="${SCRIPTDIR}/create_phenotype_with_annotations.py"
GENINF="${SCRIPTDIR}/genomic_inflation_factor.py"
WEIGHTED_LD="${SCRIPTDIR}/weighted_ld.py"
SELECT_FEATURES_PAINTOR="${SCRIPTDIR}/select_paintor_annotations.py"

START=1
END=50
NCAUSAL=2
HERITABILITY=0.4
C_PROP=0.01
NSAMPLE_TOT=13082
NCAVIAR="1 2"
NFINEMAP="2 4 6"
