#!/bin/sh
#BSUB -J _JOBNAME
#BSUB -q mpi-short
#BSUB -W 2:00
#BSUB -o _JOBNAME.out
#BSUB -e _JOBNAME.err
#BSUB -n 1

SIMNAME=_SIMDIR_
NC=_NCAUSAL

FINEMAP="${HOME}/packages/FINEMAP/finemap_v1.1_x86_64/finemap"

BASEDIR="${HOME}/fine-mapping-SNPs/artificial_phenotypes/metaprod"
SIMDIR="${BASEDIR}/simulations/${SIMNAME}"
OUTDIR="${SIMDIR}/finemap/c${NC}"
METADIR="${SIMDIR}/snptest/meta"
#LDDIR="${BASEDIR}/ldmap/combined"
LDDIR="${BASEDIR}/ldmap/weighted"

if [ -d ${OUTDIR} ]; then
    rm -rf ${OUTDIR}
fi

if [ ! -d ${OUTDIR} ]; then
    mkdir -p ${OUTDIR}
fi

CURDIR=`pwd`
cd ${OUTDIR}
echo "z;ld;snp;config;n-ind" > data
for file in ${METADIR}/Locus.[0-9]*.meta.out; do
    FBASE=`basename ${file} .meta.out`
    LOCUSFILE=${FBASE}.z
    #LDFILE="${FBASE}.LD"
    LDFILE="${FBASE}.LD"
    tail -n +2 $file > tmp.dat
    while read p; do
        RSID=`echo $p | awk '{print $2}'`
        ZSCORE=`echo $p | awk '{m=$8/$9; print m}'`
        echo $RSID $ZSCORE >> ${LOCUSFILE}
    done < tmp.dat
    rm -rf tmp.dat
    cp ${LDDIR}/${LDFILE} ${FBASE}.ld
    SNPFILE="${FBASE}.snp"
    CONFIGFILE="${FBASE}.config"
    echo "${LOCUSFILE};${FBASE}.ld;${SNPFILE};${CONFIGFILE};13082" >> data
done
${FINEMAP} --sss --in-files data --n-causal-max ${NC}
rm -rf *.ld

cd ${CURDIR}
